version: '2'
services:
  develop-db:
    image: postgres:alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432"
    networks:
      - traefik
    labels:
      - "traefik.backend=develop-db"
      - "traefik.frontend.rule=Host:develop-db.localhost"
  web:
    build: .
    volumes:
      - .:/myapp
    depends_on:
      - develop-db
    restart: always
    environment:
      DB_USERNAME: 'postgres'
      DB_PASSWORD: ''
      DB_HOST: 'develop-db'
      RACK_ENV: 'development'
      RAILS_ENV: 'development'
    ports:
      - "3000"
    networks:
      - traefik
    labels:
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host: dev.integra17-1.ing.puc.cl"

networks:
  traefik:
    external:
      name: traefik_webgateway