version: '2'
services:
  develop-redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.backend=develop-redis"
      - "traefik.frontend.rule=Host: develop-redis.localhost"
    env_file: .env
  develop-db:
    image: postgres:alpine
    volumes:
      - ./pg:/var/lib/postgresql/data
    restart: always
    networks:
      - traefik
    ports:
      - "5432"
    labels:
      - "traefik.backend=develop-db"
      - "traefik.frontend.rule=Host: develop-db.localhost"
    env_file: .env
  develop-web:
    build: .
    volumes:
      - .:/myapp
    depends_on:
      - develop-db
      - develop-redis
    restart: always
    environment:
      RAILS_ENV: 'development'
      RACK_ENV: 'development'
      POSTGRES_HOST: 'develop-db'
      REDIS_PROVIDER: 'REDIS_HOST'
      REDIS_HOST: 'develop-redis'
      DOCKER_RUNNING: 'true'
      RAILS_MAX_THREADS: '25'
    ports:
      - "3000"
    networks:
      - traefik
    labels:
      - "traefik.backend=develop-web"
      - "traefik.frontend.rule=Host: develop-web.localhost, localhost, dev.integra17-1.ing.puc.cl"
    env_file: .env

networks:
  traefik:
    external:
      name: traefik_webgateway