version: '2'
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.backend=redis"
      - "traefik.frontend.rule=Host: redis.localhost"
    env_file: .env
  db:
    image: postgres:alpine
    volumes:
      - ./pg:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432"
    networks:
      - traefik
    labels:
      - "traefik.backend=db"
      - "traefik.frontend.rule=Host: db.localhost"
    env_file: .env
  web:
    build: .
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    restart: always
    environment:
      RAILS_ENV: 'production'
      RACK_ENV: 'production'
      POSTGRES_HOST: 'db'
      REDIS_HOST: 'redis'
      DOCKER_RUNNING: 'true'
      RAILS_MAX_THREADS: '25'
    ports:
      - "3000"
    networks:
      - traefik
    labels:
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host: web.localhost, integra17-1.ing.puc.cl"
    env_file: .env

networks:
  traefik:
    external:
      name: traefik_webgateway