version: '2'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./pg:/var/lib/postgresql/data
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.backend=db"
      - "traefik.frontend.rule=Host:db.localhost"
  web:
    build: .
    volumes:
      - .:/myapp
    depends_on:
      - db
    restart: always
    environment:
      DB_USERNAME: 'postgres'
      DB_PASSWORD: ''
      DB_HOST: 'db'
      RACK_ENV: 'development'
      RAILS_ENV: 'development'
    ports:
      - "3000"
    networks:
      - traefik
    labels:
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host: integra17-1.ing.puc.cl"

networks:
  traefik:
    external:
      name: traefik_webgateway