version: '2'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
  web:
    build: .
    volumes:
      - .:/myapp
    depends_on:
      - db
    ports:
      - "2375:3000"
    restart: always
    environment:
      DB_USERNAME: 'postgres'
      DB_PASSWORD: ''
      DB_HOST: 'db'
      RACK_ENV: 'development'
      RAILS_ENV: 'development'