# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


GROUP_NUMBER: "1"

ONLINE_USER: "grupo1"

SERVER_RATE_LIMIT_TIME: "60"
CACHE_EXPIRE_TIME: "30"

API_URL_GROUP_1: "/api"
API_URL_GROUP_2: ""
API_URL_GROUP_3: "/api"
API_URL_GROUP_4: "/api"
API_URL_GROUP_5: ""
API_URL_GROUP_6: ""
API_URL_GROUP_7: "/api"
API_URL_GROUP_8: ""

development:
  GROUP_ID: "590baa00d6b4ec0004902462"
  BANK_ID: "590baa00d6b4ec000490246a"
  STORE_HOUSE_PASSWORD: "KtXf8DcNeN$I5::"
  ONLINE_PASSWORD: "1Y74E9AQ"
  CENTRAL_SERVER_URL: "https://integracion-2017-dev.herokuapp.com"
  GROUPS_SERVER_URL: "http://dev.integra17-%d.ing.puc.cl"

production:
  GROUP_ID: "5910c0910e42840004f6e680"
  BANK_ID: "5910c0910e42840004f6e688"
  STORE_HOUSE_PASSWORD: "zlSaZW5lbqAjhy8"
  ONLINE_PASSWORD: "KC5;Pt2l"
  CENTRAL_SERVER_URL: "https://integracion-2017-prod.herokuapp.com"
  GROUPS_SERVER_URL: "http://integra17-%d.ing.puc.cl"
