# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
:logfile: ./log/sidekiq.log

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - <%= `hostname`.strip %>
  - low

:schedule:
  min_stock:
    cron: '0 */30 * * * *'       # Runs every 30 minutes
    class: CheckMinimumStockWorker
  update_all_invoices:
    cron: '0 */30 * * * *'    # Runs every 30 minutes
    class: UpdateAllInvoicesWorker
  update_all_purchase_orders:
    cron: '0 */30 * * * *'    # Runs every 30 minutes
    class: UpdateAllPurchaseOrdersWorker
  check_ftp:
    cron: '0 */10 * * * *'    # Runs every 10 minutes
    class: CreateDistributorPurchaseOrdersWorker
  pending_products:
    cron: '0 * * * * *'    # Runs every minute
    class: ProduceProductsWorker
  clean_store_houses:
    cron: '0 * * * * *'    # Runs every minute
    class: CleanStoreHousesWorker
  update_groups_stock:
    cron: '0 * * * * *'    # Runs every minute
    class: UpdateGroupsStockWorker
  check_purchase_orders:
    cron: '0 * * * * *'     # Runs every minute
    class: CheckPurchaseOrdersWorker
  check_invoices:
    cron: '0 * * * * *'     # Runs every minute
    class: CheckInvoicesWorker
  update_transactions:
    cron: '0 * * * * *'     # Runs every minute
    class: BankTransactionsWorker
  update_invoices:
    cron: '0 * * * * *'     # Runs every minute
    class: UpdateInvoicesWorker
  promotions:
    cron: '0 * * * * *'     # Runs every minute
    class: PromotionsWorker
  update_store_houses:
    cron: '*/15 * * * * *'    # Runs every 15 seconds
    class: UpdateStoreHousesWorker
  update_purchase_orders:
    cron: '*/15 * * * * *'     # Runs every 15 seconds
    class: UpdatePurchaseOrdersWorker