# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: true
:concurrency: 10
:logfile: ./log/sidekiq.log

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - <%= `hostname`.strip %>
  - low

:schedule:
  pending_products:
    cron: '0 */10 * * * *'    # Runs every 10 minutes
    class: ProduceProductWorker
  check_store_houses:
    cron: '0 */10 * * * *'    # Runs every 10 minutes
    class: StoreHousesWorker
  #check_purchase_orders:
    #cron: '0 */5 * * * *'     # Runs every 5 minutes
    #class: CheckPurchaseOrdersWorker
  min_stock:
    cron: '0 0 * * * *'       # Runs every hour
    class: CheckMinimumStockWorker
  update_purchase_orders:
    cron: '0 * * * * *'    # Runs every minutes
    class: UpdatePurchaseOrdersStatusWorker
  cache:
    cron: '*/30 * * * * *'    # Runs when second = 0/30, every minute
    class: CacheWorker
  update_stock_available:
    cron: '*/30 * * * * *'    # Runs when second = 0/30, every minute
    class: UpdateStockAvailableWorker
  update_groups_stock:
    cron: '*/30 * * * * *'    # Runs when second = 0/30, every minute
    class: UpdateGroupsStockWorker

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15